HoosUp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('', include('hoosuprightnow.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^messages/', include('postman.urls')),
]

hoosuprightnow/urls.py
from django.urls import path, include
from . import views

app_name = 'hoosuprightnow'

urlpatterns = [
    # /
    path('', views.index, name = 'index'),

    # /signup
    path('signup/' , views.SignUp.as_view(), name = 'signup'),

    # /interests
    path('update_activity/' , views.update_activity, name = 'update_activity'),

    # /interests
    path('hoos_online/' , views.hoos_online, name = 'hoos_online'),
]

hoosuprightnow/models.py
from django.db import models
from django.utils.deconstruct import deconstructible
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import ast

# Create your models here.

@deconstructible
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    activity = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    class Meta:
        managed = True

hoosuprightnow/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template import Context
from django.contrib.auth import(authenticate, get_user_model, login, logout) 
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from django import forms
from django.contrib.auth.models import User
from HoosUp.middleware import get_online_now

# Create your views here.
def index(request):
    context = {
        'user': request.user
        }
    return render(request, "hoosuprightnow/index.html", context)

class SignUp(generic.CreateView):
    class SignUpForm(UserCreationForm):
        username = forms.CharField(max_length=10)
        email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

        class Meta:
            model = User
            fields = ('username', 'email', 'password1', 'password2', )
    
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'hoosuprightnow/signup.html'

def update_activity(request):
    if request.user.is_authenticated:
        request.user.profile.activity = request.POST['activity']
        request.user.save()
    
    return redirect('/hoos_online')

def hoos_online(request):
    if not request.user.is_authenticated:
        return redirect('/')

    online_users = request.online_now
    
    context = {
        'user': request.user,
        'online_users': online_users
    }

    return render(request, "hoosuprightnow/hoos_online.html", context)

hoosuprightnow/templates/base2.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta content="width=device-width, initial-scale=1.0" charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand mb-0 h1" href="{% url 'hoosuprightnow:index' %}">Hoos Up</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/messages/">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#activity-modal">Whatchya Doing?</a>
                </li>
            </ul>
            <!--<ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Log in</a>
                    {% endif %}
                </li>
            </ul>-->
            <div>
                {% if user.is_authenticated %}
                    <button class="btn btn-outline-danger my-2 my-sm-0" type="button" onclick="location.href='{% url 'logout' %}'">Log out</button>
                {% else %}
                    <button class="btn btn-outline-info my-2 my-sm-0" type="button" onclick="location.href='{% url 'login' %}'">Log in</button>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container-fluid" style="padding-top:50px">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="activity-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Whatchya Doing?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="update-activity" action="{% url 'hoosuprightnow:update_activity' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="current-activity-input">Current Activity</label>
                            <input id="current-activity-input" class="form-control" type="text" maxlength="100" value="{{user.profile.activity}}" name="activity" required>
                            <small id="activityHelp" class="form-text text-muted">Let other hoos know what your up to!</small>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success btn-block" form="update-activity">Update</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

hoosuprightnow/templates/hoosuprightnow/hoos_online.html
{% extends 'base2.html' %}

{% block title %}Hoos Online {% endblock %}

{% block content %}
    <h1 class="title">Online</h1>
    <p class="lead">Hoos online right now?</p>
    <div class="list-group pb-3">
        {% for persons in online_users %}
            {% if persons == user %}
                <a href="/messages/write/" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ persons }}</h5>
                        <span class="badge badge-primary badge-pill" style="padding-top: 6px;">You</span>
                    </div>
                    <p class="mb-1">{{ persons.profile.activity }}</p>
                </a>   
            {% else %}
                <a href="/messages/write/" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ persons }}</h5>
                    </div>
                    <p class="mb-1">{{ persons.profile.activity }}</p>
                </a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

hoosuprightnow/templates/hoosuprightnow/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Hoos Up - Activity</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hoosuprightnow/index_style_sheet.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body class="container-fluid">
    <div style="padding-top: 15%; padding-left: 10%;">
        <div class="row">
            <h1 class="text-white font-weight-light">Let's see</h1>
        </div>
        <div class="row">
            <h1 class="text-white" style="font-size: 60px;">Hoos Up</h1>
        </div>
        <div class="row mt-2">
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-outline-light" onclick="location.href='{% url 'hoosuprightnow:hoos_online' %}'">Find Some Hoos</button>
            {% else %}
                <button type="button" class="btn btn-outline-light" onclick="location.href='{% url 'login' %}'">Find Some Hoos</button>
            {% endif %}
        </div>
    </div>
]</body>
</html>

hoosuprightnow/templates/hoosuprightnow/signup.html
{% load widget_tweaks %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8" />
    <title>Hoos Up Sign up</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body class="container-fluid bg-light">
    <div class="row">
        <a class="mx-auto text-dark text-center" style="text-decoration: none;" href="{% url 'hoosuprightnow:index' %}"><h1>Hoos Up</h1></a>
    </div>
    <div class="row">
        <div class="col-lg-5 col-md-7 col-sm-8 col-10 border rounded mx-auto mt-2 bg-white">
            <h3 class="font-weight-normal mt-2 text-center">Create Account</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <div class="form-row">
                        <div class="col">
                            {{ form.username.errors }}
                            <label for="{{ form.username.id_for_label }}">Username</label>
                            {% render_field form.username class="form-control" %}
                            <small id="username-length" class="form-text">Username can be at most 10 characters</small>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    {% render_field form.email class="form-control" placeholder="email@example.com" %}
                </div>
                <div class="form-group">
                    {{ form.password1.errors }}
                    <label for="{{ form.password1.id_for_label }}">Password</label>
                    {% render_field form.password1 class="form-control" %}
                    <small id="password-length" class="form-text">Password must be at least 8 characters</small>
                </div>
                <div class="form-group">
                    {{ form.password2.errors }}
                    <label for="{{ form.password2.id_for_label }}">Re-enter Password</label>
                    {% render_field form.password2 class="form-control" %}
                </div>
                <button type="submit" class="btn btn-block btn-success">Create your account</button>
                <hr />
                <p class="text-secondary">Already have an account? <a href="{% url 'login' %}">Log in</a></p>
            </form>
        </div>
    </div>
</body>
</html>

hoosuprightnow/templates/messaging/base.html
<html>
<head>
<title>{% block title %}{% endblock %}</title>
{% block extrahead %}{% endblock %}
</head>
<body>
{% block postman_menu %}{% endblock %}
{% block content %}{% endblock %}
</body>
</html>